### ISSUE TITLE
UI for post and comments

### ISSUE THREAD

**Issue by mann27** [mann27/News24x7-Client#12]

**Comment by VarunIrani** [comment]
Here to help @mann27

**Comment by rohan2734** [comment]
@mann27  @ExpressHermes  i would llike to work on this issue.

**Comment by mann27** [comment]
@VarunIrani yeah sure. 
@rohan2734 Let's give this issue to someone else, you already have taken up 2 issues so try not to burden yourself with more work.

**Comment by rohan2734** [comment]
@mann27  no, i have taken up only one issue, and i have kept the PR , thats y i asked about this.  is @VarunIrani  part of our team?

**Comment by VarunIrani** [comment]
@rohan2734 not a part of your team but I was thinking of contribution for Hacktoberfest. I've taken up some other errands. Will get back to this later

**Comment by rohan2734** [comment]
@VarunIrani this is not labeled for hacktober fest bro,it wont count. @mann27 @ExpressHermes  please ensure that only our team members get the issues, so that we could contribute enough.

**Comment by mann27** [comment]
@rohan2734 you can take it.

**Comment by rohan2734** [comment]
@mann27  ok thanks mann, can you elaborate the issue. like where are the posts and comments? and are you expecting any ui , or shall i try something?

**Comment by mann27** [comment]
@rohan2734 take inspiration from Reddit and Facebook and try to make a more appealing layout for posts and the comments. 

Try to do something for resizing the image as per our default space so that there is no white space in it.

**Comment by rohan2734** [comment]
@mann27 @ExpressHermes  the comment button is not working?, i am not able to add any comments

**Comment by mann27** [comment]
The button is just to show the number of comments. The adding the comment button - would work only on opening the post.

**Comment by rohan2734** [comment]
> The button is just to show the number of comments. The adding the comment button - would work only on opening the post.

ok, what about images, can you show me a post where the image is not fitting so that it would be easy for me to check why and where it is not fitting.

**Comment by rohan2734** [comment]
> The button is just to show the number of comments. The adding the comment button - would work only on opening the post.

i dont see any extra button for opening the full post? how does the comment button work?

**Comment by rohan2734** [comment]
i got an idea for the posts, but i am not able to implement it, i think it is due to the material core css, what can i do?

**Comment by rohan2734** [comment]
* I have observed that here the UI is not applied, 
* So i will create a  reusable component, so that it will be used for this page, instead of writing the whole code,
* I will aslo change the background color too.
* Please consider as a improvement for this issue.
![Screenshot (132)](https://user-images.githubusercontent.com/58523134/96075157-13996480-0ec8-11eb-87d1-b826d176c3b9.png)

**Comment by rohan2734** [comment]
* I will aslo make the inline styles as classes.

**Comment by Tushardeepak** [comment]
R u working on this, if your work is over so can i take from here??

**Comment by rohan2734** [comment]
> R u working on this, if your work is over so can i take from here??

after my  pull request of my reusable POST component , you can work on its UI, because the Resuable post component is connected to this page.

**Comment by mann27** [comment]
#78 & #77 closes it
