### ISSUE TITLE
Improve UI for Login and Signup page

### ISSUE THREAD

**Issue by ExpressHermes** [mann27/News24x7-Client#39]

**Comment by Shubh1815** [comment]
I would like to work on this

**Comment by Shubh1815** [comment]
![signup](https://user-images.githubusercontent.com/59529068/95010934-aa555e00-064a-11eb-9e26-04ad21394615.png)
![login](https://user-images.githubusercontent.com/59529068/95010938-ae817b80-064a-11eb-987a-e4b73737d1e0.png)
will this do??

**Comment by ExpressHermes** [comment]
Looks good!

**Comment by mann27** [comment]
Yeah, this will do, What is the loading animation when you click the button. ( disable the login/signup button and add a loader instead of text ). @Shubh1815

**Comment by mann27** [comment]
Also, what is the UI for the error messages when you enter invalid input.

**Comment by Shubh1815** [comment]
![error](https://user-images.githubusercontent.com/59529068/95013356-5b64f400-065d-11eb-975d-d863277fb231.png)

I have used Alerts for DB errors and CircularProgress for loader. The loader will show up in the button once the user clicks it.

**Comment by mann27** [comment]
Yeah looks great! Nice work. Submit the pr.
