### ISSUE TITLE
Update UI of FAQs in help page

### ISSUE THREAD

**Issue by ExpressHermes** [mann27/News24x7-Client#42]

**Comment by mann27** [comment]
![Screenshot 2020-10-05 at 1 06 57 PM](https://user-images.githubusercontent.com/33790390/95051993-c967f480-070b-11eb-958a-58f9b7fe1ee3.png)


Try making the UI resembling this. Where on clicking on the question the answer should appear.

**Comment by mann27** [comment]
- [ ] Remove the image which is currently there in the page.

**Comment by rohan2734** [comment]
i would like to work on this issue.

**Comment by ExpressHermes** [comment]
Go for it!
