### ISSUE TITLE
Home Button needed in Navbar

### ISSUE THREAD

**Issue by rohan2734** [mann27/News24x7-Client#58]
* i dont know the status of issue #40 
* Currently the users dont have the option to navigate back to home page, 
* they have to click the back option present on their browser,
* instead they can easily navigate to home page using Home Button in the Navbar.
* I am working on this.

**Comment by Tushardeepak** [comment]
Home button is there in navbar..
And its is included in #40 by itself

**Comment by rohan2734** [comment]
> Home button is there in navbar..
> And its is included in #40 by itself

ok i will check, but till now it wasnt included right?,when did you add it?

**Comment by Tushardeepak** [comment]
Its obvious, in navbar I have to add a home button for feed page and a button to landing page also, I am working on that.
These button issues are included in #40 I will do that.

**Comment by Tushardeepak** [comment]
Home button is there If you click on the Logo button, But I will create a separate button for that in future.

**Comment by rohan2734** [comment]
> Home button is there If you click on the Logo button, But I will create a separate button for that in future.

i know that we will go to home page when we click on logo , but not every user knows it , so i have created a issue and i will complete it. you have already done ur updates in the navbar.hope u understand.

**Comment by Tushardeepak** [comment]
no I am still working on the navbar, But if want u can add a button of home page , no problem

**Comment by rohan2734** [comment]
> no I am still working on the navbar, But if want u can add a button of home page , no problem

ya thankyou for your understanding. you can pull the changes as soon as i update it.
