### ISSUE TITLE
Image width to be modified

### ISSUE THREAD

**Issue by rohan2734** [mann27/News24x7-Client#62]
* refering to the issue #12 
![image](https://user-images.githubusercontent.com/58523134/96442408-b46d8400-1228-11eb-828f-cb78a340aa3d.png)12

* currently the image with is not fitting the whole post, 
* or atleast the padding should be decreased.
* I tried but it was not working
* anyone can work on this issue.

**Comment by mann27** [comment]
#77 closes it
